const regions = ['Adilabad, India', 'Agar, India', 'Agra, India',
  'Ahmedabad city, India', 'Ahmedabad rural, India',
  'Ahmednagar, India', 'Aizawl, India', 'Ajmer, India',
  'Akola, India', 'Alapuzha, India', 'Aligarh, India',
  'Alipurduar, India', 'Alirajpur, India', 'Allahabad, India',
  'Almora, India', 'Alwar, India', 'Ambala (rural), India',
  'Ambala (urban), India', 'Ambedkar nagar, India', 'Amethi, India',
  'Amravati commr., India', 'Amravati rural, India', 'Amreli, India',
  'Amritsar rural, India', 'Amroha, India', 'Anand, India',
  'Anantapur, India', 'Anantnag, India', 'Angul, India',
  'Anjaw, India', 'Anti terrorist squad, India', 'Anuppur, India',
  'Araria, India', 'Ariyalur, India', 'Arvalli, India',
  'Arwal, India', 'Asansol-durgapur pc, India', 'Ashok nagar, India',
  'Auraiya, India', 'Aurangabad, India', 'Aurangabad commr., India',
  'Aurangabad rural, India', 'Awantipora, India', 'Azamgarh, India',
  'Badaun, India', 'Baddi, India', 'Bagaha, India',
  'Bagalkot, India', 'Bageshwar, India', 'Baghpat, India',
  'Bahraich, India', 'Balaghat, India', 'Balasore, India',
  'Ballari, India', 'Ballia, India', 'Balod, India',
  'Balodbazar, India', 'Balrampur, India', 'Banaskantha, India',
  'Banda, India', 'Bandipora, India', 'Banka, India',
  'Bankura, India', 'Banswara, India', 'Barabanki, India',
  'Baragarh, India', 'Baramulla, India', 'Baran, India',
  'Bareilly, India', 'Barmer, India', 'Barnala, India',
  'Barpeta, India', 'Barrackpur pc, India', 'Barwani, India',
  'Baska, India', 'Basti, India', 'Batala, India', 'Bathinda, India',
  'Beed, India', 'Begusarai, India', 'Belagavi city, India',
  'Belagavi district, India', 'Bemetra, India',
  'Bengaluru city, India', 'Bengaluru district, India',
  'Berhampur, India', 'Bettiah, India', 'Betul, India',
  'Bhabhua, India', 'Bhadrak, India', 'Bhagalpur, India',
  'Bhandara, India', 'Bharatpur, India', 'Bharuch, India',
  'Bhavnagar, India', 'Bhilwara, India', 'Bhind, India',
  'Bhiwani, India', 'Bhojpur, India', 'Bhopal, India',
  'Bhopal railway, India', 'Bidar, India', 'Bidhannagar pc, India',
  'Bijnor, India', 'Bikaner, India', 'Bilaspur, India',
  'Birbhum, India', 'Bishnupur, India', 'Bizapur, India',
  'Bokaro, India', 'Bolangir, India', 'Bongaigaon, India',
  'Botad, India', 'Boudh, India', 'Budgam, India',
  'Bulandshahar, India', 'Buldhana, India', 'Bundi, India',
  'Burdwan, India', 'Burhanpur, India', 'Buxar, India',
  'C. i. d., India', 'C. i. d. crime, India', 'Cid, India',
  'Cp amritsar, India', 'Cp jalandhar, India', 'Cp ludhiana, India',
  'Cachar, India', 'Central, India', 'Chaibasa, India',
  'Chamarajnagar, India', 'Chamba, India', 'Chamoli, India',
  'Champawat, India', 'Champhai, India', 'Chandel, India',
  'Chandigarh, India', 'Chandoli, India', 'Chandrapur, India',
  'Changlang, India', 'Chatra, India', 'Chennai, India',
  'Chhatarpur, India', 'Chhindwara, India', 'Chhotaudepur, India',
  'Chikkaballapura, India', 'Chikkamagaluru, India',
  'Chirang, India', 'Chitradurga, India', 'Chitrakoot, India',
  'Chittoor, India', 'Chittorgarh, India', 'Churachandpur, India',
  'Churu, India', 'Coimbatore, India', 'Coimbatore city, India',
  'Coochbehar, India', 'Crime branch, India', 'Crime jammu, India',
  'Crime srinagar, India', 'Cuddalore, India', 'Cuddapah, India',
  'Cuttack, India', 'Cyber cell, India', 'Cyberabad, India',
  'D&n haveli, India', 'Dcp bbsr, India', 'Dcp ctc, India',
  'Dahod, India', 'Dakshin dinajpur, India',
  'Dakshina kannada, India', 'Daman, India', 'Damoh, India',
  'Dang, India', 'Dantewara, India', 'Darbhanga, India',
  'Darjeeling, India', 'Darrang, India', 'Datia, India',
  'Dausa, India', 'Davanagere, India', 'Dehradun, India',
  'Deogarh, India', 'Deoghar, India', 'Deoria, India',
  'Devbhumi dwarka, India', 'Dewas, India', 'Dhalai, India',
  'Dhamtari, India', 'Dhanbad, India', 'Dhanbad railway, India',
  'Dhar, India', 'Dharmapuri, India', 'Dharwad, India',
  'Dhemaji, India', 'Dhenkanal, India', 'Dholpur, India',
  'Dhubri, India', 'Dhule, India', 'Dibang valley, India',
  'Dibrugarh, India', 'Dimapur, India', 'Dindigul, India',
  'Dindori, India', 'Diu, India', 'Doda, India', 'Dumka, India',
  'Dungarpur, India', 'Durg, India', 'Eow, India', 'East, India',
  'East godavari, India', 'Economic offences unit, India',
  'Ernakulam commr., India', 'Ernakulam rural, India',
  'Erode, India', 'Etah, India', 'Etawah, India', 'Faizabad, India',
  'Faridabad, India', 'Faridkot, India', 'Fatehabad, India',
  'Fatehgarh, India', 'Fatehgarh sahib, India', 'Fatehpur, India',
  'Fazilka, India', 'Ferozepur, India', 'Firozabad, India',
  'G. r. p., India', 'G. r. p. raipur, India', 'G.r.p.ajmer, India',
  'G.r.p.jodhpur, India', 'Gadag, India', 'Gadchiroli, India',
  'Gajapati, India', 'Ganderbal, India', 'Gandhinagar, India',
  'Ganganagar, India', 'Ganjam, India', 'Garhwa, India',
  'Gariyaband, India', 'Garo hills east, India',
  'Garo hills north, India', 'Garo hills south, India',
  'Garo hills south west, India', 'Garo hills west, India',
  'Gautambudh nagar, India', 'Gaya, India', 'Ghaziabad, India',
  'Ghazipur, India', 'Gir somnath, India', 'Giridih, India',
  'Goalpara, India', 'Godda, India', 'Golaghat, India',
  'Gomati, India', 'Gonda, India', 'Gondia, India',
  'Gopalganj, India', 'Gorakhpur, India', 'Gumla, India',
  'Guna, India', 'Guntakal railway, India', 'Guntur, India',
  'Guntur urban, India', 'Gurdaspur, India', 'Gurgaon, India',
  'Guwahati city, India', 'Gwalior, India', 'Hailakandi, India',
  'Hamirpur, India', 'Handwara, India', 'Hanumangarh, India',
  'Hapur, India', 'Harda, India', 'Hardoi, India', 'Haridwar, India',
  'Hassan, India', 'Hathras, India', 'Haveri, India',
  'Hazaribagh, India', 'Hingoli, India', 'Hissar, India',
  'Hooghly, India', 'Hoshangabad, India', 'Hoshiarpur, India',
  'Howrah g. r. p., India', 'Howrah pc, India',
  'Howrah rural, India', 'Hubballi dharwad city, India',
  'Hyderabad city, India', 'Igi airport, India', 'Idukki, India',
  'Imphal east, India', 'Imphal west, India', 'Indore, India',
  'Indore railway, India', 'Irrigation & power, India',
  'Jabalpur, India', 'Jabalpur railway, India',
  'Jagatsinghpur, India', 'Jagdalpur, India',
  'Jaintia hills east, India', 'Jaintia hills west, India',
  'Jaipur east, India', 'Jaipur north, India', 'Jaipur rural, India',
  'Jaipur south, India', 'Jaipur west, India', 'Jaisalmer, India',
  'Jajpur, India', 'Jalandhar rural, India', 'Jalaun, India',
  'Jalgaon, India', 'Jalna, India', 'Jalore, India',
  'Jalpaiguri, India', 'Jamalpur railway, India', 'Jammu, India',
  'Jamnagar, India', 'Jamshedpur, India',
  'Jamshedpur railway, India', 'Jamtara, India', 'Jamui, India',
  'Janjgir, India', 'Jashpur, India', 'Jaunpur, India',
  'Jehanabad, India', 'Jhabua, India', 'Jhajjar, India',
  'Jhalawar, India', 'Jhansi, India',
  'Jhargram police district, India', 'Jharsuguda, India',
  'Jhunjhunu, India', 'Jind, India', 'Jodhpur east, India',
  'Jodhpur rural, India', 'Jodhpur west, India', 'Jorhat, India',
  'Junagadh, India', 'K.g.f., India', 'K.railways, India',
  'Kabirdham, India', 'Kachchh east(g), India',
  'Kachchh west(b), India', 'Kaithal, India', 'Kalaburgi, India',
  'Kalahandi, India', 'Kameng east, India', 'Kameng west, India',
  'Kamrup, India', 'Kanchipuram, India', 'Kandhamal, India',
  'Kangra, India', 'Kanker, India', 'Kannauj, India',
  'Kannur, India', 'Kanpur dehat, India', 'Kanpur nagar, India',
  'Kanyakumari, India', 'Kapurthala, India', 'Karaikal, India',
  'Karauli, India', 'Karbi anglong, India', 'Kargil, India',
  'Karimganj, India', 'Karimnagar, India', 'Karnal, India',
  'Karur, India', 'Kasargod, India', 'Kasganj, India',
  'Kathua, India', 'Katihar, India', 'Katihar railway, India',
  'Katni, India', 'Kaushambi, India', 'Kendrapara, India',
  'Keonjhar, India', 'Khagaria, India', 'Khammam, India',
  'Khandwa, India', 'Khanna, India', 'Kharagpur g. r. p., India',
  'Khargone, India', 'Khasi hills east, India',
  'Khasi hills south west, India', 'Khasi hills west, India',
  'Kheda, India', 'Khiri, India', 'Khunti, India', 'Khurda, India',
  'Kinnaur, India', 'Kiphire, India', 'Kishanganj, India',
  'Kishtwar, India', 'Kodagu, India', 'Koderma, India',
  'Kohima, India', 'Kokrajhar, India', 'Kolar, India',
  'Kolasib, India', 'Kolhapur, India', 'Kolkata, India',
  'Kollam commr., India', 'Kollam rural, India', 'Kondagaon, India',
  'Koppal, India', 'Koraput, India', 'Korba, India', 'Koriya, India',
  'Kota city, India', 'Kota rural, India', 'Kottayam, India',
  'Kowai, India', 'Kozhikode commr., India',
  'Kozhikode rural, India', 'Krishna, India', 'Krishnagiri, India',
  'Kukung kumey, India', 'Kulgam, India', 'Kullu, India',
  'Kupwara, India', 'Kurnool, India', 'Kurukshetra, India',
  'Kushi nagar, India', 'Lahaul & spiti, India', 'Lakhimpur, India',
  'Lakhisarai, India', 'Lakshadweep, India', 'Lalitpur, India',
  'Latehar, India', 'Latur, India', 'Lawngtlai, India', 'Leh, India',
  'Lohardagga, India', 'Lohit, India', 'Longding, India',
  'Longleng, India', 'Lower dibang valley, India', 'Lucknow, India',
  'Ludhiana rural, India', 'Lunglei, India', 'Madhepura, India',
  'Madhubani, India', 'Madurai, India', 'Madurai city, India',
  'Mahaboob nagar, India', 'Maharajganj, India', 'Mahasamund, India',
  'Mahendergarh, India', 'Mahisagar, India', 'Mahoba, India',
  'Mainpuri, India', 'Malappuram, India', 'Malda, India',
  'Malkangiri, India', 'Mamit, India', 'Mandi, India',
  'Mandla, India', 'Mandsaur, India', 'Mandya, India',
  'Mangaluru city, India', 'Mansa, India', 'Mathura, India',
  'Mau, India', 'Mayurbhanj, India', 'Medak, India', 'Meerut, India',
  'Mehsana, India', 'Metro, India', 'Mewat, India',
  'Mirzapur, India', 'Moga, India', 'Mokokchung, India',
  'Mon, India', 'Moradabad, India', 'Morbi, India', 'Morena, India',
  'Morigaon, India', 'Motihari, India', 'Muktsar, India',
  'Mumbai commr., India', 'Mumbai railway, India', 'Mungali, India',
  'Munger, India', 'Murshidabad, India', 'Muzaffarnagar, India',
  'Muzaffarpur, India', 'Muzaffarpur railway, India',
  'Mysuru city, India', 'Mysuru district, India',
  'N. c. hills, India', 'Nabarangpur, India', 'Nadia, India',
  'Nagaon, India', 'Nagapattinam, India', 'Nagaur, India',
  'Nagpur commr., India', 'Nagpur railway, India',
  'Nagpur rural, India', 'Nainital, India', 'Nalanda, India',
  'Nalbari, India', 'Nalgonda, India', 'Namakkal, India',
  'Nanded, India', 'Nandurbar, India', 'Narayanpur, India',
  'Narmada, India', 'Narsinghpur, India', 'Nasik commr., India',
  'Nasik rural, India', 'Naugachia, India', 'Navi mumbai, India',
  'Navsari, India', 'Nawadah, India', 'Nayagarh, India',
  'Neemuch, India', 'Nellore, India', 'New delhi, India',
  'Nicobar, India', 'Nilgiris, India', 'Nizamabad, India',
  'North, India', 'North & middle andaman, India',
  'North 24 parganas, India', 'North goa, India',
  'North-east, India', 'North-west, India', 'Nuapada, India',
  'Osmanabad, India', 'Other units, India', 'Outer, India',
  'Pakur, India', 'Palakkad, India', 'Palamu, India',
  'Palghar, India', 'Pali, India', 'Palwal, India',
  'Panchkula, India', 'Panchmahal, India', 'Panipat, India',
  'Panna, India', 'Papum pare city, India',
  'Papum pare rural, India', 'Parbhani, India',
  'Paschim medinipur, India', 'Patan, India',
  'Pathanamthitta, India', 'Pathankot, India', 'Patiala, India',
  'Patna, India', 'Patna railway, India', 'Pauri garhwal, India',
  'Perambalur, India', 'Peren, India', 'Phek, India',
  'Pilibhit, India', 'Pithoragarh, India', 'Poonch, India',
  'Porbandar, India', 'Praapgarh, India', 'Prakasham, India',
  'Pratapgarh, India', 'Puducherry, India', 'Pudukottai, India',
  'Pulwama, India', 'Pune commr., India', 'Pune railway, India',
  'Pune rural, India', 'Purab medinipur, India', 'Puri, India',
  'Purnea, India', 'Purulia, India', 'Railway, India',
  'Raibareilly, India', 'Raichur, India', 'Raigad, India',
  'Raigarh, India', 'Railway chennai, India',
  'Railway trichy, India', 'Railways, India',
  'Railways jammu, India', 'Railways kashmir, India',
  'Railways katra, India', 'Raipur, India', 'Raisen, India',
  'Rajahmundry, India', 'Rajgarh, India', 'Rajkot city, India',
  'Rajkot rural, India', 'Rajnandgaon, India', 'Rajouri, India',
  'Rajsamand, India', 'Ramanagar, India', 'Ramban, India',
  'Ramgarh, India', 'Ramnathapuram, India', 'Rampur, India',
  'Ranchi, India', 'Ranga reddy, India', 'Ratlam, India',
  'Ratnagiri, India', 'Rayagada, India', 'Reasi, India',
  'Rewa, India', 'Rewari, India', 'Ri-bhoi, India', 'Rohtak, India',
  'Rohtas, India', 'Ropar, India', 'Rourkela, India',
  'Rudra prayag, India', 'Sas nagar, India', 'Sbs nagar, India',
  'Spuwac, India', 'Srp (cuttack), India', 'Srp (rourkela), India',
  'Sabarkantha, India', 'Sagar, India', 'Saharanpur, India',
  'Saharsa, India', 'Sahebganj, India', 'Saiha, India',
  'Salem, India', 'Salem city, India', 'Samastipur, India',
  'Samba, India', 'Sambalpur, India', 'Sambhal, India',
  'Sangli, India', 'Sangrur, India', 'Sant kabirnagar, India',
  'Saraikela, India', 'Saran, India', 'Sarguja, India',
  'Satara, India', 'Satna, India', 'Sawai madhopur, India',
  'Sealdah g. r. p., India', 'Secunderabad railway, India',
  'Sehore, India', 'Senapati, India', 'Seoni, India',
  'Serchhip, India', 'Shahdol, India', 'Shahjahanpur, India',
  'Shajapur, India', 'Shamli, India', 'Sheikhpura, India',
  'Sheohar, India', 'Sheopur, India', 'Shimla, India',
  'Shimoga, India', 'Shivpuri, India', 'Shopian, India',
  'Shrawasti, India', 'Siang east, India', 'Siang upper, India',
  'Siang west, India', 'Sibsagar, India', 'Sidharthnagar, India',
  'Sidhi, India', 'Sikar, India', 'Siliguri g. r. p., India',
  'Siliguri pc, India', 'Simdega, India', 'Sindhudurg, India',
  'Singrauli, India', 'Sipahijala, India', 'Sirmaur, India',
  'Sirohi, India', 'Sirsa, India', 'Sitamarhi, India',
  'Sitapur, India', 'Sivagangai, India', 'Siwan, India',
  'Solan, India', 'Solapur commr., India', 'Solapur rural, India',
  'Sonbhadra, India', 'Sonepur, India', 'Sonipat, India',
  'Sonitpur, India', 'Sopore, India', 'South, India',
  'South 24 parganas, India', 'South andaman, India',
  'South goa, India', 'South-east, India', 'South-west, India',
  'Spl cell, India', 'Spl traffic, India', 'Srikakulam, India',
  'Srinagar, India', 'St.ravidasnagar, India',
  'Subansiri lower, India', 'Subansiri upper, India', 'Sukma, India',
  'Sultanpur, India', 'Sundargarh, India', 'Supaul, India',
  'Surajpur, India', 'Surat city, India', 'Surat rural, India',
  'Surendranagar, India', 'Tamenglong, India', 'Tapi, India',
  'Tarn taran, India', 'Tawang, India', 'Tehri garhwal, India',
  'Thane commr., India', 'Thane rural, India', 'Thanjavur, India',
  'Theni, India', 'Thirunelveli, India', 'Thirunelveli city, India',
  'Thiruvallur, India', 'Thiruvannamalai, India',
  'Thiruvarur, India', 'Thoothugudi, India', 'Thoubal, India',
  'Thrissur commr., India', 'Thrissur rural, India',
  'Tikamgarh, India', 'Tinsukia, India', 'Tirap, India',
  'Tirupathi urban, India', 'Tiruppur, India',
  'Tiruppur city, India', 'Tonk, India', 'Total, India',
  'Trichy, India', 'Trichy city, India', 'Trivandrum commr., India',
  'Trivandrum rural, India', 'Tuensang, India', 'Tumakuru, India',
  'Udaipur, India', 'Udalguri, India', 'Udhampur, India',
  'Udhamsingh nagar, India', 'Udupi, India', 'Ujjain, India',
  'Ukhrul, India', 'Umaria, India', 'Una, India', 'Unakoti, India',
  'Unnao, India', 'Uttar dinajpur, India', 'Uttara kannada, India',
  'Uttarkashi, India', 'Vadodara city, India',
  'Vadodara rural, India', 'Vaishali, India', 'Valsad, India',
  'Varanasi, India', 'Vellore, India', 'Vidisha, India',
  'Vigilance, India', 'Vijayapura, India', 'Vijayawada city, India',
  'Vijayawada railway, India', 'Villupuram, India',
  'Virudhunagar, India', 'Visakha rural, India',
  'Visakhapatnam, India', 'Vizianagaram, India',
  'W.rly  ahmedabad, India', 'W.rly vadodara, India',
  'Warangal, India', 'Warangal urban, India', 'Wardha, India',
  'Washim, India', 'Wayanadu, India', 'West, India',
  'West godavari, India', 'Wokha, India', 'Yadgiri, India',
  'Yamunanagar, India', 'Yavatmal, India', 'Zunheboto, India'];

  export default regions;